name: Gerar Relatorio PDF
on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar a biblioteca correta
      run: pip install fpdf2

    - name: Executar o Script
      run: python gerar_relatorio.py

    - name: Disponibilizar PDF para Download
      uses: actions/upload-artifact@v4
      with:
        name: Relatorio-PDF
        path: Relatorio_Iluminacao_Publica_Atualizado_Definitivo.pdf
